FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    g++ \
    python3 \
    python3-dev \
    python3-pip \
    pkg-config \
    sqlite3 \
    git \
    mercurial \
    libxml2-dev \
    libxslt1-dev \
    build-essential \
    cmake \
    libgsl-dev \
    libgtk-3-dev \
    libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install matplotlib numpy pandas

RUN git clone https://gitlab.com/nsnam/ns-3-dev.git /ns-3-dev
WORKDIR /ns-3-dev
RUN ./ns3 configure --enable-examples --enable-tests --enable-modules=core,network,internet,point-to-point,applications,traffic-control,flow-monitor
RUN ./ns3 build

COPY video_streaming_qos.cc /ns-3-dev/scratch/

WORKDIR /ns-3-dev